# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.76775581 0.70652427 0.79158689 ... 0.65308366 0.64529144 0.91194709]
 [0.09641337 0.25587904 0.23460107 ... 0.92782663 0.95747311 0.14549176]
 [0.0775842  0.5649449  0.3362841  ... 0.63401388 0.84206167 0.50446552]
 ...
 [0.66007706 0.22479947 0.50520454 ... 0.6130543  0.95833281 0.20158098]
 [0.53863648 0.49200018 0.11049167 ... 0.38455401 0.26571049 0.35794141]
 [0.46108755 0.76659714 0.58970633 ... 0.96723798 0.26993034 0.6117993 ]]
[[0.48249617 0.13895182 0.94685338 ... 0.04513068 0.74374029 0.98383274]
 [0.70566276 0.19110665 0.82433161 ... 0.74951351 0.99358214 0.12465545]
 [0.77943645 0.5060576  0.87901593 ... 0.94065521 0.49745124 0.08204051]
 ...
 [0.17207164 0.80680183 0.49662882 ... 0.05127298 0.9616327  0.55271493]
 [0.92152296 0.22310052 0.76887318 ... 0.36362318 0.02259805 0.52884832]
 [0.70583741 0.96186678 0.10840802 ... 0.87961624 0.61047604 0.72828519]]


Без использования numpy

In [ ]:
def mult(a, b):
    rows_a, cols_a =a.shape
    rows_b, cols_b =b.shape

    result= []
    for i in range (rows_a):
      row=[]
      for j in range (cols_b):
        element=0
        for k in range (cols_a):
          element += a[i][k] * b[k][j]
        row.append(element)
      result.append(row)
    return result


C использованием numpy

In [ ]:
def np_mult(a, b):
    result= np.dot(a,b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 617 ms, sys: 0 ns, total: 617 ms
Wall time: 626 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 720 µs, sys: 5.03 ms, total: 5.75 ms
Wall time: 10.7 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4910739309925702e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.9420838  0.3297986  0.34100903] [0.54255313 0.98191684 0.62522213]


In [ ]:
def scalar_product(a,b):
    s=[]
    for i in range (len(a)):
      res=a[i]*b[i]
      s.append(res)
    return s

In [ ]:
def np_scalar_product(a,b):
    s= np.dot(a, b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 24 µs, sys: 0 ns, total: 24 µs
Wall time: 28.6 µs
CPU times: user 218 µs, sys: 0 ns, total: 218 µs
Wall time: 633 µs


2.096343415813006

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** сама по себе библиотека предоставляет оптимизированные функции и алгоритмы написанные на низкоуровневых языках таких как c или fortran


------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag_elem= np.diagonal(a)
  sum=0
  for element in diag_elem:
    if len(diag_elem) == 0:
      return 0
    if (element%2==0):
      sum+=element
  return sum

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 2, 3, 7, 8],
       [1, 7, 6, 5, 1],
       [5, 6, 3, 8, 8],
       [9, 6, 4, 3, 8],
       [3, 5, 2, 6, 3]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 50.1 µs


0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(x):
    x_reshape=x.reshape(1000, -1)
    cumsum=np.cumsum(x_reshape, axis=1)
    n=np.arange(1,x_reshape.shape[1]+1)
    result=cumsum/n[:, np.newaxis]
    return result.reshape(x.shape)

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.74783147 0.04381648 0.11274355 0.80421021 0.13401654 0.37310345
 0.01671469 0.23845405 0.95225492 0.4297374  0.88435293 0.67394087
 0.55810185 0.72517428 0.94354779 0.97474082 0.5607485  0.64268436
 0.36923767 0.56402089 0.33061014 0.50993188 0.99540775 0.28878548
 0.34958912 0.62113775 0.94773546 0.10822052 0.34828738 0.23236519
 0.70487239 0.3000932  0.45858543 0.54408235 0.87422033 0.56729397
 0.77151892 0.91486552 0.45203914 0.8660165  0.47961487 0.71815501
 0.1469542  0.13133434 0.65299527 0.13622942 0.55504085 0.56223566
 0.40872163 0.26900283 0.39768282 0.97734952 0.39335605 0.11026646
 0.79877192 0.38711615 0.2419263  0.3187049  0.42936974 0.38319458
 0.54667119 0.20978582 0.79251065 0.29908042 0.41684211 0.68273439
 0.7240287  0.13681964 0.0886469  0.16909117 0.42953244 0.07991903
 0.95055735 0.74993182 0.97779622 0.40046168 0.36921204 0.43559196
 0.21502086 0.53350141 0.79396513 0.2486609  0.58957489 0.12965552
 0.17044374 0.70261482 0.83884234 0.22164414 0.89745805 0.6693

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    x=np.array([])
    num=np.array([])
    if len(a)>0:
      x=np.array([k for k, _ in groupby(a)])
      num=np.array([len(list(g)) for _, g in groupby(a)])
    return x, num

In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 68 µs, sys: 0 ns, total: 68 µs
Wall time: 73.9 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [ ]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result= np.copy(X)
    result[1::2]=a
    result[0::2]=result[0::2]**3
    result=result[::-1]
    result=np.concatenate((X, result))
    return result

In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 209 µs, sys: 22 µs, total: 231 µs
Wall time: 766 µs
